<wsdl:definitions name="ewalletProxyMerchantDsService" targetNamespace="http://www.atos.net/awl/bfi/ita/wallet/interbank/proxy/services/ws/soap/merchantds" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.atos.net/awl/bfi/ita/wallet/interbank/proxy/services/ws/soap/merchantds" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://www.atos.net/awl/bfi/ita/wallet/interbank/proxy/services/ws/soap/merchantds/">
   <wsdl:import location="https://gitlab.intra.monext.fr/payline/paylinev4/-/raw/develop/paylib-client/src/main/resources/EwalletProxyMerchantDsWebServiceImpl.wsdl" namespace="http://www.atos.net/awl/bfi/ita/wallet/interbank/proxy/services/ws/soap/merchantds/"/>
   <wsdl:binding name="ewalletProxyMerchantDsServiceSoapBinding" type="ns1:ewalletProxyMerchantDsWebService">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="joinMerchant">
         <soap:operation soapAction="http://www.atos.net/awl/bfi/ita/wallet/interbank/proxy/services/ws/soap/ewallet/joinMerchant" style="document"/>
         <wsdl:input name="joinMerchant">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="joinMerchantResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="ewalletProxyMerchantDsService">
      <wsdl:port binding="tns:ewalletProxyMerchantDsServiceSoapBinding" name="ewalletProxyMerchantDsWebServicePort">
         <soap:address location="https://ssl-liv-ws-merchant-proxy.ewallet.aw.atos.net/interbank-proxy/webservices/EwalletProxyMerchantDsWebServiceImpl"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>